export const surpriseMePrompts = [
    'uma poltrona em forma de abacate',
    'uma pintura a óleo surrealista e sonhada por Salvador Dalí de um gato jogando damas',
    'ursos de pelúcia fazendo compras de comida no Japão, estilo ukiyo-e',
    'uma pintura a óleo de Matisse de um robô humanoide jogando xadrez',
    'um pandinha cientista maluco misturando químicos brilhantes, arte digital',
    "uma fotografia macro de 35mm de dois ratos no Havaí, cada um vestindo um biquíni minúsculo e carregando uma prancha de surfe minúscula, arte digital",
    'uma renderização 3D de um peixe tropical fofo em um aquário sobre um fundo azul escuro, arte digital',
    'um astronauta descansando em um resort tropical no espaço, estilo vaporwave',
    'um retrato a óleo de uma capivara usando roupas medievais reais e uma coroa ornada sobre um fundo escuro',
    'uma janela de vidro colorido que retrata um hambúrguer e batatas fritas',
    'um desenho a lápis e aquarela de uma cidade brilhante no futuro com carros voadores',
    'um salão interior iluminado pelo sol com uma piscina com água clara e outra piscina com água rosa translúcida, ao lado de uma grande janela, arte digital',
    'um shiba inu que prevê o futuro lendo sua sorte em um hambúrguer gigante, arte digital',
    'uma lontra marinha com um brinco de pérola" por Johannes Vermeer',
    'um desenho a pastel de óleo de um gato irritado em uma nave espacial',
    'uma pintura de uma raposa no estilo de Noite Estrelada',
    'uma tigela de sopa que parece um monstro, tricotada de lã',
    'Um brinquedo de pelúcia robô sentado contra uma parede amarela',
    'Um pôr-do-sol estilo synthwave acima da água reflexiva do mar, arte digital',
    'Duas torres futuristas com uma ponte aérea coberta de vegetação exuberante, arte digital',
    'Uma renderização 3D de um balão de ar quente colorido como um arco-íris voando acima de um lago reflexivo',
    'Uma capa de quadrinhos de um super-herói usando fones de ouvido',
    'Uma explosão colorida de pó no meio de um fundo preto',
    'Uma foto de um cachorro Samoyed com a língua fora abraçando um gato Siamese branco',
    'Uma foto de um monstro de pelo branco em pé em um quarto roxo',
    "Uma foto da escultura de David de Michelangelo usando fones de ouvido djing",
    'Um Samurai montando um cavalo em Marte, lomografia.',
    'Um Cadillac moderno e elegante dirigindo pela Gardiner Expressway com o centro de Toronto ao fundo, com um raio de lente, fotografia de 50mm',
    'Uma fotografia realista de uma jovem mulher com olhos azuis e cabelos loiros',
    'Um homem em frente a uma estrela para outra dimensão',
    'Bob Esponja Quadrado na Blair Witch Project',
    'Um Velociraptor trabalhando em uma barraca de cachorro-quente, lomografia',
    'Um homem caminhando pelas ruas movimentadas de Kowloon à noite, iluminado por muitos sinais de neon brilhantes, lente de 50mm',
    'Um churrasco que está vivo, no estilo de um filme animado da Pixar',
    'Um clube de dança futurista ciborgue, luzes neon',
    'A perdida Star Wars 1990 Anime Japonês',
    'Um hambúrguer em forma de cubo de Rubik, fotografia profissional de comida',
    'Um Ouriço Synthwave, Blade Runner Cyberpunk',
    'Um astronauta encontrando uma forma de vida alienígena em um planeta distante, fotografia',
    'Um dinossauro explorando Cape Town, fotografia',
    'Um homem se apaixonando por seu computador, arte digital',
    'Uma fotografia de um ciborgue explorando Tóquio à noite, lomografia',
    'Drácula caminhando pelas ruas de Nova York na década de 1920, fotografia em preto e branco',
    'Aeronave Synthwave',
    'Um homem se perde nas ruas chuvosas de Tóquio, com sinais neon brilhantes, 50mm',
    'Um ônibus espacial voando acima de Cape Town, arte digital',
];